### ISSUE TITLE
How to install as a docker container like eufy-security-ws

### ISSUE THREAD

**Issue by mjvracing** [bropat/hassio-eufy-security-ws#19]
### Add-on version

Latest

### Architecture

aarch64

### HomeAssistant version

2023.6.2

### Operating System type

Docker

### Operating system version

Unraid  Linux 5.10.28-Unraid x86_64

### Describe the bug

Hi there, is there a way of installing this in a docker container like there was with the original eufy-security-ws that appears to have been depreciated? Unfortunately I've lost access to my eufy equipment due to this change. 

### To reproduce

2. Click on '...'

**Comment by djthread** [comment]
I'm also running HA under docker, so I would need to run this under a container.

**Comment by djthread** [comment]
Ah! Nevermind, I got going by installing HACS, searching `eufy` there and following the good docs. I set up a couple of things alongside my Home Assistant docker-compose config:

```
  eufy-security-ws:
    image: bropat/eufy-security-ws:latest
    network_mode: "host"
    restart: always
    environment:
      - USERNAME=me@myplace.com
      - PASSWORD=mypassword
      - PORT=4989
    volumes:
      - /data/eufy-security-ws:/data

  rtsp-server:
    image: bluenviron/mediamtx:latest
    ports:
      - 8554:8554
      - 1935:1935
    environment:
      - RTSP_PROTOCOLS=tcp
```
